---- project 1 -------------
INSERT INTO TASK (TITLE, TYPE_CODE, STATUS_CODE, PROJECT_ID, SPRINT_ID, STARTPOINT)
values ('Data', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Trees', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI', 'epic', 'in_progress', 1, 1, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Sprint', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Project', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Task', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Attachments', 'story', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Dashboard', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Report of Sprint (UI)', 'story', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Organizational-architectural', 'epic', 'in_progress', 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'), ---- project 2 -------------
       ('Title', 'task', 'todo', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'canceled', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_test', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_test', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_test', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'story', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'bug', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'epic', 'in_progress', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_review', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_review', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'story', 'ready_for_test', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'review', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'bug', 'review', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'epic', 'test', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'story', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'bug', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'canceled', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'canceled', 2, 2, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_test', 2, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'in_progress', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 3, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_test', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_test', 2, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'story', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'bug', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'todo', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'epic', 'in_progress', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_review', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'ready_for_review', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'story', 'ready_for_test', 2, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'review', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'bug', 'review', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'test', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'epic', 'test', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'story', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'bug', 'done', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Title', 'task', 'canceled', 2, 4, now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('subproject sprint task', 'epic', 'in_progress', 4, 5,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('subproject backlog task', 'epic', 'in_progress', 4, null,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds');

INSERT INTO TASK (TITLE, TYPE_CODE, STATUS_CODE, PROJECT_ID, SPRINT_ID, PARENT_ID, STARTPOINT)
values ('Add role manager and filters in security', 'task', 'done', 1, 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Add users from task-timing', 'task', 'ready_for_review', 1, 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Add tasks-2 in DB', 'task', 'in_progress', 1, 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Remove reference with USER_TYPE IN (3,4,5)', 'task', 'in_progress', 1, 1, 1,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('REST API for trees', 'task', 'in_progress', 1, 1, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Drawing in trees', 'task', 'in_progress', 1, 1, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Context menu', 'task', 'in_progress', 1, 1, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Reassignment sprint', 'task', 'in_progress', 1, 1, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Add task, subtask, sprint, subsprint', 'task', 'in_progress', 1, 1, 2,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Make layout for view TitleTo', 'task', 'in_progress', 1, 1, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Make layout for edit TitleTo', 'task', 'in_progress', 1, 1, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Fix header-fragment', 'task', 'ready_for_review', 1, 1, 3,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('REST API', 'task', 'in_progress', 1, 1, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Tests', 'task', 'in_progress', 1, 1, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI view, mock button to dashboard', 'task', 'in_progress', 1, 1, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI edit', 'task', 'in_progress', 1, 1, 4,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('REST API', 'task', 'in_progress', 1, 1, 5,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Tests', 'task', 'in_progress', 1, 1, 5,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI view, mock button to dashboard', 'task', 'in_progress', 1, 1, 5,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI edit', 'task', 'in_progress', 1, 1, 5,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('REST API', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Tests', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI view, mock button to dashboard', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI edit', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI view add to Task, mock button to dashboard', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI edit add to Task', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Edit changelog with changes of Task model', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('REST API: changeStatus', 'task', 'in_progress', 1, 1, 6,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Make columns with tasks', 'task', 'in_progress', 1, 1, 8,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('UI tab of tasks', 'task', 'in_progress', 1, 1, 8,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Context mune', 'task', 'in_progress', 1, 1, 8,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Duration, count of tasks, elapsed time', 'task', 'in_progress', 1, 1, 9,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Meeting, dividing tasks', 'task', 'in_progress', 1, 1, 10,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Refactoring packages', 'task', 'in_progress', 1, 1, 10,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Refactoring tasks', 'task', 'in_progress', 1, 1, 10,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Subproject sprint subtask', 'task', 'in_progress', 4, 5, 87,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds'),
       ('Subproject backlog subtask', 'task', 'in_progress', 4, null, 88,
        now() + random() * interval '5 minutes' + random() * interval '20 seconds');
alter
    sequence TASK_ID_SEQ restart with 1000;