ALTER TABLE TASK
    DROP
        COLUMN DESCRIPTION;
ALTER TABLE TASK
    DROP
        COLUMN PRIORITY_CODE;
ALTER TABLE TASK
    DROP
        COLUMN ESTIMATE;
ALTER TABLE TASK
    DROP
        COLUMN UPDATED;
